"""
Secure Vision AI - Derived Metrics Module

Role:
    Analytics Engineer

Purpose:
    Calculate classification performance metrics for the complete
    validation and test predictions generated by batch_predictor.py.

Input:
    data/processed/batch_predictions.csv

Required columns:
    model
    split
    true_index
    predicted_index

Outputs:
    data/processed/metrics/

    <model>_<split>_summary.csv
    <model>_<split>_per_class.csv
    <model>_<split>_confusion_matrix.csv

Example:
    baseline_cnn_validation_summary.csv
    baseline_cnn_test_summary.csv
    resnet18_validation_summary.csv
    resnet18_test_summary.csv
"""


from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
)


# ==========================================================
# CONFIGURATION
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

INPUT_PATH = PROCESSED_DIR / "batch_predictions.csv"

METRICS_DIR = PROCESSED_DIR / "metrics"


CLASS_NAMES = [
    "airplane",
    "automobile",
    "bird",
    "cat",
    "deer",
    "dog",
    "frog",
    "horse",
    "ship",
    "truck",
]

NUM_CLASSES = len(CLASS_NAMES)

CLASS_LABELS = list(range(NUM_CLASSES))

MODEL_NAMES = (
    "baseline_cnn",
    "resnet18",
)

SPLITS = (
    "validation",
    "test",
)


# ==========================================================
# INPUT VALIDATION
# ==========================================================

def _to_integer_labels(values, name):
    """
    Convert a label array to int64.

    Accepts integer values and floats that represent
    whole numbers.

    Rejects:
        - booleans
        - strings
        - NaN
        - infinity
        - fractional values
    """

    array = np.asarray(values)

    if array.ndim != 1:
        raise ValueError(
            f"{name} must be a one-dimensional array."
        )

    if array.dtype == bool:
        raise ValueError(
            f"{name} cannot contain boolean values."
        )

    if not np.issubdtype(array.dtype, np.number):
        raise ValueError(
            f"{name} must contain numeric class indices."
        )

    if np.issubdtype(array.dtype, np.floating):

        if not np.all(np.isfinite(array)):
            raise ValueError(
                f"{name} contains NaN or infinite values."
            )

        if not np.all(array == np.floor(array)):
            raise ValueError(
                f"{name} must contain whole-number class labels."
            )

    return array.astype(np.int64)


def _validate_labels(y_true, y_pred):
    """
    Validate actual and predicted CIFAR-10 labels.
    """

    y_true = _to_integer_labels(
        y_true,
        "y_true",
    )

    y_pred = _to_integer_labels(
        y_pred,
        "y_pred",
    )

    if len(y_true) == 0:
        raise ValueError(
            "Cannot calculate metrics for an empty dataset."
        )

    if len(y_true) != len(y_pred):
        raise ValueError(
            "y_true and y_pred must have the same length."
        )

    for name, labels in (
        ("y_true", y_true),
        ("y_pred", y_pred),
    ):

        if np.any(labels < 0) or np.any(labels >= NUM_CLASSES):
            raise ValueError(
                f"{name} contains labels outside the "
                f"valid range 0 to {NUM_CLASSES - 1}."
            )

    return y_true, y_pred


# ==========================================================
# CALCULATE METRICS
# ==========================================================

def calculate_metrics(y_true, y_pred):
    """
    Calculate overall and per-class classification metrics.

    Returns:
        Dictionary containing:

        summary
        confusion_matrix
        per_class
    """

    y_true, y_pred = _validate_labels(
        y_true,
        y_pred,
    )

    # ------------------------------------------------------
    # Overall metrics
    # ------------------------------------------------------

    accuracy = accuracy_score(
        y_true,
        y_pred,
    )

    macro_precision = precision_score(
        y_true,
        y_pred,
        labels=CLASS_LABELS,
        average="macro",
        zero_division=0,
    )

    macro_recall = recall_score(
        y_true,
        y_pred,
        labels=CLASS_LABELS,
        average="macro",
        zero_division=0,
    )

    macro_f1 = f1_score(
        y_true,
        y_pred,
        labels=CLASS_LABELS,
        average="macro",
        zero_division=0,
    )

    weighted_f1 = f1_score(
        y_true,
        y_pred,
        labels=CLASS_LABELS,
        average="weighted",
        zero_division=0,
    )

    # ------------------------------------------------------
    # Confusion matrix
    # ------------------------------------------------------

    matrix = confusion_matrix(
        y_true,
        y_pred,
        labels=CLASS_LABELS,
    )

    # ------------------------------------------------------
    # Per-class metrics
    # ------------------------------------------------------

    report_dict = classification_report(
        y_true,
        y_pred,
        labels=CLASS_LABELS,
        target_names=CLASS_NAMES,
        output_dict=True,
        zero_division=0,
    )

    per_class = pd.DataFrame(
        {
            class_name: report_dict[class_name]
            for class_name in CLASS_NAMES
        }
    ).T

    per_class.index.name = "class_name"

    per_class = per_class.reset_index()

    # ------------------------------------------------------
    # Summary
    # ------------------------------------------------------

    summary = {
        "sample_count": int(len(y_true)),
        "accuracy": float(accuracy),
        "macro_precision": float(macro_precision),
        "macro_recall": float(macro_recall),
        "macro_f1": float(macro_f1),
        "weighted_f1": float(weighted_f1),
    }

    return {
        "summary": summary,
        "confusion_matrix": matrix,
        "per_class": per_class,
    }


# ==========================================================
# DISPLAY
# ==========================================================

def print_metrics(
    results,
    model_name,
    split_name,
):
    """
    Display metrics in the terminal.
    """

    summary = results["summary"]

    print("\n" + "=" * 60)
    print("SECURE VISION AI - MODEL EVALUATION")
    print("=" * 60)

    print(f"Model             : {model_name}")
    print(f"Split             : {split_name}")

    print(f"Number of samples : {summary['sample_count']}")
    print(f"Accuracy          : {summary['accuracy']:.4f}")
    print(f"Macro Precision   : {summary['macro_precision']:.4f}")
    print(f"Macro Recall      : {summary['macro_recall']:.4f}")
    print(f"Macro F1 Score    : {summary['macro_f1']:.4f}")
    print(f"Weighted F1 Score : {summary['weighted_f1']:.4f}")

    print("\nCONFUSION MATRIX")
    print(
        "Rows = actual class; columns = predicted class"
    )

    matrix_df = pd.DataFrame(
        results["confusion_matrix"],
        index=CLASS_NAMES,
        columns=CLASS_NAMES,
    )

    print(matrix_df.to_string())

    print("\nPER-CLASS METRICS")

    print(
        results["per_class"]
        .round(4)
        .to_string(index=False)
    )


# ==========================================================
# SAVE REPORTS
# ==========================================================

def save_metrics(
    results,
    model_name,
    split_name,
):
    """
    Save summary, per-class metrics and confusion matrix.
    """

    METRICS_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    prefix = f"{model_name}_{split_name}"

    summary_path = (
        METRICS_DIR
        / f"{prefix}_summary.csv"
    )

    per_class_path = (
        METRICS_DIR
        / f"{prefix}_per_class.csv"
    )

    matrix_path = (
        METRICS_DIR
        / f"{prefix}_confusion_matrix.csv"
    )

    # Summary

    pd.DataFrame(
        [results["summary"]]
    ).to_csv(
        summary_path,
        index=False,
    )

    # Per-class metrics

    results["per_class"].to_csv(
        per_class_path,
        index=False,
    )

    # Confusion matrix

    matrix_df = pd.DataFrame(
        results["confusion_matrix"],
        index=CLASS_NAMES,
        columns=CLASS_NAMES,
    )

    matrix_df.index.name = "actual_class"

    matrix_df.to_csv(
        matrix_path
    )

    print("\nMetric reports saved:")

    print(summary_path)
    print(per_class_path)
    print(matrix_path)

    return {
        "summary_path": summary_path,
        "per_class_path": per_class_path,
        "confusion_matrix_path": matrix_path,
    }


# ==========================================================
# LOAD BATCH PREDICTIONS
# ==========================================================

def load_batch_predictions(csv_path):
    """
    Load and validate batch_predictions.csv.

    Returns:
        Clean pandas DataFrame.
    """

    csv_path = Path(csv_path)

    if not csv_path.exists():
        raise FileNotFoundError(
            f"Batch prediction file not found:\n"
            f"{csv_path}\n\n"
            "Run first:\n"
            "python -m src.validations.batch_predictor"
        )

    df = pd.read_csv(csv_path)

    required_columns = {
        "model",
        "split",
        "true_index",
        "predicted_index",
    }

    missing_columns = (
        required_columns - set(df.columns)
    )

    if missing_columns:
        raise ValueError(
            "batch_predictions.csv is missing required "
            "columns: "
            + ", ".join(sorted(missing_columns))
        )

    df = df.dropna(
        subset=[
            "model",
            "split",
            "true_index",
            "predicted_index",
        ]
    ).copy()

    if df.empty:
        raise ValueError(
            "batch_predictions.csv contains no usable rows."
        )

    # Convert labels

    df["true_index"] = pd.to_numeric(
        df["true_index"],
        errors="raise",
    )

    df["predicted_index"] = pd.to_numeric(
        df["predicted_index"],
        errors="raise",
    )

    # Validate numeric values

    for column in (
        "true_index",
        "predicted_index",
    ):

        values = df[column].to_numpy()

        if not np.all(np.isfinite(values)):
            raise ValueError(
                f"{column} contains NaN or infinite values."
            )

        if not np.all(
            values == np.floor(values)
        ):
            raise ValueError(
                f"{column} must contain whole-number labels."
            )

        if np.any(values < 0) or np.any(
            values >= NUM_CLASSES
        ):
            raise ValueError(
                f"{column} must contain labels from "
                f"0 to {NUM_CLASSES - 1}."
            )

    df["true_index"] = df[
        "true_index"
    ].astype(int)

    df["predicted_index"] = df[
        "predicted_index"
    ].astype(int)

    return df.reset_index(drop=True)


# ==========================================================
# EVALUATE ONE MODEL / SPLIT
# ==========================================================

def evaluate_model_split(
    df,
    model_name,
    split_name,
):
    """
    Evaluate one model on one dataset split.
    """

    subset = df[
        (df["model"] == model_name)
        & (df["split"] == split_name)
    ].copy()

    if subset.empty:
        raise ValueError(
            f"No predictions found for "
            f"model='{model_name}', "
            f"split='{split_name}'."
        )

    y_true = subset[
        "true_index"
    ].to_numpy()

    y_pred = subset[
        "predicted_index"
    ].to_numpy()

    results = calculate_metrics(
        y_true,
        y_pred,
    )

    print_metrics(
        results,
        model_name,
        split_name,
    )

    save_metrics(
        results,
        model_name,
        split_name,
    )

    return results


# ==========================================================
# MAIN
# ==========================================================

def main():

    print("=" * 60)
    print("Secure Vision AI - Derived Metrics")
    print("=" * 60)

    print(f"\nProject root    : {PROJECT_ROOT}")
    print(f"Processed data  : {PROCESSED_DIR}")
    print(f"Input file      : {INPUT_PATH}")

    print("\nLoading batch predictions...")

    try:

        df = load_batch_predictions(
            INPUT_PATH
        )

    except (
        ValueError,
        FileNotFoundError,
    ) as error:

        print(f"\nError: {error}")
        return

    print(
        f"Loaded {len(df):,} prediction rows."
    )

    print(
        "\nAvailable models: "
        + ", ".join(
            sorted(df["model"].unique())
        )
    )

    print(
        "Available splits: "
        + ", ".join(
            sorted(df["split"].unique())
        )
    )

    evaluated = 0

    for model_name in MODEL_NAMES:

        for split_name in SPLITS:

            print(
                f"\nEvaluating "
                f"{model_name} / {split_name}..."
            )

            try:

                evaluate_model_split(
                    df,
                    model_name,
                    split_name,
                )

                evaluated += 1

            except ValueError as error:

                print(
                    f"\nSkipping "
                    f"{model_name} / {split_name}: "
                    f"{error}"
                )

    print("\n" + "=" * 60)

    if evaluated:

        print(
            "Derived metrics evaluation completed "
            f"({evaluated} model/split evaluations)."
        )

        print(
            f"Reports are stored in:\n"
            f"{METRICS_DIR}"
        )

    else:

        print(
            "No model/split combinations were evaluated."
        )

    print("=" * 60)


if __name__ == "__main__":
    main()