table anomaly_summary
	lineageTag: bc222bc1-047f-4dc5-8ade-c7c945235912

	column feature
		dataType: string
		lineageTag: cd152d47-fed0-46f5-a111-8206480f8896
		summarizeBy: none
		sourceColumn: feature

		annotation SummarizationSetBy = Automatic

	column q1
		dataType: double
		lineageTag: 89a7cbb7-d722-40fa-9172-7c7edb06b875
		summarizeBy: sum
		sourceColumn: q1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column q3
		dataType: double
		lineageTag: bed05408-19d6-4eb5-8a73-c787be2728f5
		summarizeBy: sum
		sourceColumn: q3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column iqr
		dataType: double
		lineageTag: 22bbe1a3-e474-45eb-9566-edb692223ef1
		summarizeBy: sum
		sourceColumn: iqr

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lower_bound
		dataType: double
		lineageTag: 002b97a2-c10a-4aa0-911a-756d50356c43
		summarizeBy: sum
		sourceColumn: lower_bound

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column upper_bound
		dataType: double
		lineageTag: eddce3c8-b701-47de-b720-94f9661f44c4
		summarizeBy: sum
		sourceColumn: upper_bound

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column outlier_count
		dataType: double
		lineageTag: 848836fb-33cf-4c0b-8136-f5b6120ba42f
		summarizeBy: sum
		sourceColumn: outlier_count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column outlier_percentage
		dataType: double
		lineageTag: 92e135a9-34dc-44ae-a983-0750d7b429f3
		summarizeBy: sum
		sourceColumn: outlier_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition anomaly_summary = m
		mode: import
		source =
				let
									Source = Table.FromRows({
				                    {"brightness", 99.40201568603516, 139.83243560791016, 40.430419921875, 38.756385803222656, 200.47806549072263, 820, 1.64},
				                    {"contrast", 43.76808738708496, 63.33176898956299, 19.563681602478027, 14.42256498336792, 92.67729139328004, 200, 0.4},
				                    {"red_mean", 103.86279296875, 145.414794921875, 41.552001953125, 41.5347900390625, 207.7427978515625, 771, 1.542},
				                    {"green_mean", 101.88720703125, 142.41943359375, 40.5322265625, 41.0888671875, 203.2177734375, 839, 1.678},
				                    {"blue_mean", 86.325927734375, 138.565673828125, 52.23974609375, 7.96630859375, 216.92529296875, 352, 0.7040000000000001}
									}, {"feature", "q1", "q3", "iqr", "lower_bound", "upper_bound", "outlier_count", "outlier_percentage"}),
									#"Changed Type" = Table.TransformColumnTypes(Source, {{"feature", type text}, {"q1", type number}, {"q3", type number}, {"iqr", type number}, {"lower_bound", type number}, {"upper_bound", type number}, {"outlier_count", type number}, {"outlier_percentage", type number}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

