table class_distribution
	lineageTag: 7954dec3-ffd1-4b50-a63b-2941da58731b

	column class_id
		dataType: double
		lineageTag: f963b6ee-2990-47d9-9f7a-07f40286906e
		summarizeBy: sum
		sourceColumn: class_id

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column class_name
		dataType: string
		lineageTag: f008cc8d-9e30-48ee-b115-ea9856dbdce8
		summarizeBy: none
		sourceColumn: class_name

		annotation SummarizationSetBy = Automatic

	column image_count
		dataType: double
		lineageTag: 217b153d-68d1-40ee-a841-c6cbdacc9212
		summarizeBy: sum
		sourceColumn: image_count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column percentage
		dataType: double
		lineageTag: 732ff9fb-198f-4a65-8ec1-0a22b9f3790a
		summarizeBy: sum
		sourceColumn: percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition class_distribution = m
		mode: import
		source =
				let
									Source = Table.FromRows({
				                    {0, "airplane", 5000, 10.0},
				                    {1, "automobile", 5000, 10.0},
				                    {2, "bird", 5000, 10.0},
				                    {3, "cat", 5000, 10.0},
				                    {4, "deer", 5000, 10.0},
				                    {5, "dog", 5000, 10.0},
				                    {6, "frog", 5000, 10.0},
				                    {7, "horse", 5000, 10.0},
				                    {8, "ship", 5000, 10.0},
				                    {9, "truck", 5000, 10.0}
									}, {"class_id", "class_name", "image_count", "percentage"}),
									#"Changed Type" = Table.TransformColumnTypes(Source, {{"class_id", type number}, {"class_name", type text}, {"image_count", type number}, {"percentage", type number}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

