table data_quality_report
	lineageTag: 2027fa30-a049-4285-8f20-1121864c2440

	column dataset
		dataType: string
		lineageTag: 264639fb-66e3-4691-b80b-4755dca96358
		summarizeBy: none
		sourceColumn: dataset

		annotation SummarizationSetBy = Automatic

	column check
		dataType: string
		lineageTag: 23c89714-7d1e-47a5-a005-3fb63877f8df
		summarizeBy: none
		sourceColumn: check

		annotation SummarizationSetBy = Automatic

	column value
		dataType: string
		lineageTag: 28d15c6c-31f1-43b2-9d99-7cb4e9714309
		summarizeBy: none
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	column status
		dataType: string
		lineageTag: 8b610dbb-9073-4746-aef3-a111b9effbb3
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	partition data_quality_report = m
		mode: import
		source =
				let
									Source = Table.FromRows({
				                    {"TRAIN", "Sample Count", "50000", "PASS"},
				                    {"TEST", "Sample Count", "10000", "PASS"},
				                    {"TRAIN", "Missing Values", "0", "PASS"},
				                    {"TEST", "Missing Values", "0", "PASS"},
				                    {"TRAIN", "Pixel Range", "0-255", "PASS"},
				                    {"TEST", "Pixel Range", "0-255", "PASS"},
				                    {"TRAIN", "Invalid Labels", "0", "PASS"},
				                    {"TEST", "Invalid Labels", "0", "PASS"},
				                    {"TRAIN", "Duplicate Images", "0", "PASS"},
				                    {"TEST", "Duplicate Images", "0", "PASS"},
				                    {"TRAIN/TEST", "Exact Image Overlap", "0", "PASS"},
				                    {"TRAIN", "Class Distribution - airplane", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - automobile", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - bird", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - cat", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - deer", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - dog", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - frog", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - horse", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - ship", "5000 (10.00%)", "INFO"},
				                    {"TRAIN", "Class Distribution - truck", "5000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - airplane", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - automobile", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - bird", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - cat", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - deer", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - dog", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - frog", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - horse", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - ship", "1000 (10.00%)", "INFO"},
				                    {"TEST", "Class Distribution - truck", "1000 (10.00%)", "INFO"}
									}, {"dataset", "check", "value", "status"}),
									#"Changed Type" = Table.TransformColumnTypes(Source, {{"dataset", type text}, {"check", type text}, {"value", type text}, {"status", type text}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

