table model_performance_summary
	lineageTag: 83ada603-aa02-4ca4-bda5-8ca8482edbdd

	column model
		dataType: string
		lineageTag: 0ed12b2e-3a3a-4b74-b2e8-8f4362c66022
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column split
		dataType: string
		lineageTag: 52a71bab-0f6a-41a7-8825-333a29e94927
		summarizeBy: none
		sourceColumn: split

		annotation SummarizationSetBy = Automatic

	column sample_count
		dataType: double
		lineageTag: 09a0bca6-1979-4821-8c94-7811965b8fe1
		summarizeBy: sum
		sourceColumn: sample_count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accuracy
		dataType: double
		lineageTag: 2f807347-b3da-42a4-8bd5-8ff91a9828b5
		summarizeBy: sum
		sourceColumn: accuracy

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column macro_precision
		dataType: double
		lineageTag: 57ae181f-d65b-432b-8fbd-c242d5a77ade
		summarizeBy: sum
		sourceColumn: macro_precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column macro_recall
		dataType: double
		lineageTag: 4fb517b1-46ea-45be-bfa8-d38c928857c3
		summarizeBy: sum
		sourceColumn: macro_recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column macro_f1
		dataType: double
		lineageTag: 9814a9f4-22df-4077-bd40-25f43ad5a3e4
		summarizeBy: sum
		sourceColumn: macro_f1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weighted_f1
		dataType: double
		lineageTag: 11302c0d-05da-425f-8ffb-a64886230a85
		summarizeBy: sum
		sourceColumn: weighted_f1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition model_performance_summary = m
		mode: import
		source =
				let
									Source = Table.FromRows({
				                    {"Baseline CNN", "Test", 10000.0, 0.7975, 0.7969107813029364, 0.7975, 0.7970124822582733, 0.7970124822582733},
				                    {"Baseline CNN", "Validation", 5000.0, 0.7926, 0.7945381988004517, 0.7926, 0.7933324170659976, 0.7933324170659977},
				                    {"ResNet18", "Test", 10000.0, 0.9041, 0.903884396933598, 0.9041, 0.9038652148494386, 0.9038652148494388},
				                    {"ResNet18", "Validation", 5000.0, 0.9092, 0.9095864108992722, 0.9092, 0.9093257511868632, 0.9093257511868632}
									}, {"model", "split", "sample_count", "accuracy", "macro_precision", "macro_recall", "macro_f1", "weighted_f1"}),
									#"Changed Type" = Table.TransformColumnTypes(Source, {{"model", type text}, {"split", type text}, {"sample_count", type number}, {"accuracy", type number}, {"macro_precision", type number}, {"macro_recall", type number}, {"macro_f1", type number}, {"weighted_f1", type number}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

