table per_class_metrics
	lineageTag: 6acd54a0-196b-4929-848d-daba8b7cb300

	column class_name
		dataType: string
		lineageTag: 300267a6-2298-445e-8b4f-42b3f2ac8b9c
		summarizeBy: none
		sourceColumn: class_name

		annotation SummarizationSetBy = Automatic

	column precision
		dataType: double
		lineageTag: 169e4210-961f-470b-83c8-faf23461bfb0
		summarizeBy: sum
		sourceColumn: precision

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column recall
		dataType: double
		lineageTag: 04481217-3c9a-4263-a677-14a556851f06
		summarizeBy: sum
		sourceColumn: recall

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column f1-score
		dataType: double
		lineageTag: c14b6117-786d-4af8-b553-b1dad502fc1f
		summarizeBy: sum
		sourceColumn: f1-score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column support
		dataType: double
		lineageTag: 93be9a8f-e8a2-4713-b335-69933d0ef876
		summarizeBy: sum
		sourceColumn: support

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column model
		dataType: string
		lineageTag: bca8ece7-3ad7-4b4d-a400-c06a4fb88ab6
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column split
		dataType: string
		lineageTag: 6b93d17a-ada5-4bf8-9706-2e3f211553b6
		summarizeBy: none
		sourceColumn: split

		annotation SummarizationSetBy = Automatic

	partition per_class_metrics = m
		mode: import
		source =
				let
									Source = Table.FromRows({
				                    {"airplane", 0.8060724779627816, 0.823, 0.8144482929242949, 1000.0, "Baseline CNN", "Test"},
				                    {"automobile", 0.905284147557328, 0.908, 0.90664003994009, 1000.0, "Baseline CNN", "Test"},
				                    {"bird", 0.7316062176165803, 0.706, 0.7185750636132315, 1000.0, "Baseline CNN", "Test"},
				                    {"cat", 0.6319663512092534, 0.601, 0.6160943106099436, 1000.0, "Baseline CNN", "Test"},
				                    {"deer", 0.7712287712287712, 0.772, 0.7716141929035483, 1000.0, "Baseline CNN", "Test"},
				                    {"dog", 0.7026239067055393, 0.723, 0.7126663380975851, 1000.0, "Baseline CNN", "Test"},
				                    {"frog", 0.8074766355140187, 0.864, 0.8347826086956521, 1000.0, "Baseline CNN", "Test"},
				                    {"horse", 0.8446700507614213, 0.832, 0.8382871536523929, 1000.0, "Baseline CNN", "Test"},
				                    {"ship", 0.899492385786802, 0.886, 0.8926952141057934, 1000.0, "Baseline CNN", "Test"},
				                    {"truck", 0.8686868686868687, 0.86, 0.864321608040201, 1000.0, "Baseline CNN", "Test"},
				                    {"airplane", 0.9027504911591356, 0.919, 0.910802775024777, 1000.0, "ResNet18", "Test"},
				                    {"automobile", 0.9533267130089376, 0.96, 0.9566517189835576, 1000.0, "ResNet18", "Test"},
				                    {"bird", 0.8763931104356636, 0.865, 0.8706592853548062, 1000.0, "ResNet18", "Test"},
				                    {"cat", 0.8109243697478992, 0.772, 0.7909836065573771, 1000.0, "ResNet18", "Test"},
				                    {"deer", 0.8773764258555133, 0.923, 0.8996101364522417, 1000.0, "ResNet18", "Test"},
				                    {"dog", 0.8475247524752475, 0.856, 0.8517412935323383, 1000.0, "ResNet18", "Test"},
				                    {"frog", 0.92992992992993, 0.929, 0.9294647323661832, 1000.0, "ResNet18", "Test"},
				                    {"horse", 0.9381338742393508, 0.925, 0.9315206445115812, 1000.0, "ResNet18", "Test"},
				                    {"ship", 0.948948948948949, 0.948, 0.9484742371185592, 1000.0, "ResNet18", "Test"},
				                    {"truck", 0.9535353535353536, 0.944, 0.9487437185929648, 1000.0, "ResNet18", "Test"}
									}, {"class_name", "precision", "recall", "f1-score", "support", "model", "split"}),
									#"Changed Type" = Table.TransformColumnTypes(Source, {{"class_name", type text}, {"precision", type number}, {"recall", type number}, {"f1-score", type number}, {"support", type number}, {"model", type text}, {"split", type text}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

