table threshold_summary
	lineageTag: bc861cfb-201c-4d3c-ad2a-7ec712b8beae

	column model
		dataType: string
		lineageTag: d5149a8b-065b-47dc-901c-21f51e798500
		summarizeBy: none
		sourceColumn: model

		annotation SummarizationSetBy = Automatic

	column tuning_split
		dataType: string
		lineageTag: dcb063d7-2408-4349-9825-6433f7f37288
		summarizeBy: none
		sourceColumn: tuning_split

		annotation SummarizationSetBy = Automatic

	column reporting_split
		dataType: string
		lineageTag: 7c676b00-7fc3-4e66-8bbc-e964f9efee86
		summarizeBy: none
		sourceColumn: reporting_split

		annotation SummarizationSetBy = Automatic

	column optimal_threshold
		dataType: double
		lineageTag: 0058761c-bb83-406e-8469-21342ef38f54
		summarizeBy: sum
		sourceColumn: optimal_threshold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column samples_reported
		dataType: double
		lineageTag: 7971b20b-cbb4-4360-9085-a2f8aaf7ea0e
		summarizeBy: sum
		sourceColumn: samples_reported

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column coverage
		dataType: double
		lineageTag: f3d3e170-29be-4a52-8ce7-afb9dbf2bbb4
		summarizeBy: sum
		sourceColumn: coverage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_rate
		dataType: double
		lineageTag: 8ab15a54-9668-4667-aa4d-fee0d2eb3713
		summarizeBy: sum
		sourceColumn: review_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column accuracy_accepted
		dataType: double
		lineageTag: 247845a4-93d4-4a52-bb5e-92c5b9a43a55
		summarizeBy: sum
		sourceColumn: accuracy_accepted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column errors_accepted
		dataType: double
		lineageTag: c9cdf701-8cfd-48e1-aba5-1321ecb6e7c9
		summarizeBy: sum
		sourceColumn: errors_accepted

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column errors_caught_by_review
		dataType: double
		lineageTag: 78d4e04d-99d6-4c3b-bde1-d412ec2d830e
		summarizeBy: sum
		sourceColumn: errors_caught_by_review

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_cost
		dataType: double
		lineageTag: 8dc345bd-36aa-4dfb-9941-72fffbdd42b8
		summarizeBy: sum
		sourceColumn: total_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cost_per_1000
		dataType: double
		lineageTag: b60432fd-cb3b-42e6-81b1-484573f3d065
		summarizeBy: sum
		sourceColumn: cost_per_1000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column trust_all_cost_per_1000
		dataType: double
		lineageTag: 92604c92-4c6d-4439-a4db-f378b52521e8
		summarizeBy: sum
		sourceColumn: trust_all_cost_per_1000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column review_all_cost_per_1000
		dataType: double
		lineageTag: bbf66b94-6695-479b-a25b-05f3e56a4267
		summarizeBy: sum
		sourceColumn: review_all_cost_per_1000

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column savings_vs_trust_all_pct
		dataType: double
		lineageTag: ad5e67d5-4aab-4c60-8ba2-53764e5b1c39
		summarizeBy: sum
		sourceColumn: savings_vs_trust_all_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column savings_vs_review_all_pct
		dataType: double
		lineageTag: 1e43bc1c-c57c-48fa-ad55-d52de343499d
		summarizeBy: sum
		sourceColumn: savings_vs_review_all_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column best_possible_threshold_on_report_split
		dataType: double
		lineageTag: 612c4cb5-c8cf-4161-98df-8bdf18882712
		summarizeBy: sum
		sourceColumn: best_possible_threshold_on_report_split

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition threshold_summary = m
		mode: import
		source =
				let
									Source = Table.FromRows({
				                    {"baseline_cnn", "validation", "test", 0.96, 10000, 0.3619, 0.6381, 0.9853550704614534, 53, 1972, 7176.0, 717.6, 3037.5, 1000.0, 76.37530864197531, 28.24, 0.95},
				                    {"resnet18", "validation", "test", 0.98, 10000, 0.7268, 0.2732, 0.9836268574573472, 119, 840, 4517.0, 451.7, 1438.5, 1000.0, 68.59923531456377, 54.83, 0.99}
									}, {"model", "tuning_split", "reporting_split", "optimal_threshold", "samples_reported", "coverage", "review_rate", "accuracy_accepted", "errors_accepted", "errors_caught_by_review", "total_cost", "cost_per_1000", "trust_all_cost_per_1000", "review_all_cost_per_1000", "savings_vs_trust_all_pct", "savings_vs_review_all_pct", "best_possible_threshold_on_report_split"}),
									#"Changed Type" = Table.TransformColumnTypes(Source, {{"model", type text}, {"tuning_split", type text}, {"reporting_split", type text}, {"optimal_threshold", type number}, {"samples_reported", type number}, {"coverage", type number}, {"review_rate", type number}, {"accuracy_accepted", type number}, {"errors_accepted", type number}, {"errors_caught_by_review", type number}, {"total_cost", type number}, {"cost_per_1000", type number}, {"trust_all_cost_per_1000", type number}, {"review_all_cost_per_1000", type number}, {"savings_vs_trust_all_pct", type number}, {"savings_vs_review_all_pct", type number}, {"best_possible_threshold_on_report_split", type number}})
								in
									#"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

